# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_sessions', '0002_auto_20171008_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesession',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
