# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('challenge_sessions', '0003_auto_20171008_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesession',
            name='challenge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='challenges.Challenge'),
        ),
    ]
