# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:36
from __future__ import unicode_literals

import apps.ninjas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ninja',
            managers=[
                ('objects', apps.ninjas.models.NinjaManager()),
            ],
        ),
    ]
