# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20171011_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='signup_end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
