# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_auto_20171008_1136'),
        ('challenges', '0004_auto_20171011_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='planned_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_planned', to='ninjas.Ninja'),
        ),
    ]
