# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_planned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='signup_end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
