# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninjas', '0002_auto_20171008_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_bout_losses', to='ninjas.Ninja')),
                ('participants', models.ManyToManyField(related_name='participated_session_bouts', to='ninjas.Ninja')),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_bout_wins', to='ninjas.Ninja')),
            ],
        ),
    ]
