# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_bouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbout',
            name='loser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_bout_losses', to='ninjas.Ninja'),
        ),
        migrations.AlterField(
            model_name='sessionbout',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_bout_wins', to='ninjas.Ninja'),
        ),
    ]
