# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_sessions', '0003_auto_20171008_1630'),
        ('session_bouts', '0002_auto_20171008_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbout',
            name='challenge_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='challenge_sessions.ChallengeSession'),
        ),
    ]
